add SearchLive SearchPhotos SearchVideos
n0madic/twitter-scraper pull request #19
Opened 2020-12-19 17:28 UTC by JustHumanz

add realtime searching and filtering tweets like photos/videos only

2020-12-21 12:32 UTC, n0madic commented
Name of methods that change properties will confuse with SearchTweets...
From the comments can see that there was originally a `Set` prefix, I think it's worth returning it

2020-12-21 12:41 UTC, JustHumanz commented
hemm make sense,wait a sec

2020-12-22 10:22 UTC, n0madic requested changes
ok?

2020-12-22 10:36 UTC, JustHumanz commented on search.go
> +	if s.searchMode == "live" {
ah right,i never thinking about that

2020-12-22 10:36 UTC, JustHumanz commented
sure

2020-12-23 14:49 UTC, JustHumanz reviewed
lgtm

2020-12-23 16:40 UTC, n0madic commented
no more changes?

2020-12-23 16:50 UTC, JustHumanz reviewed
yeah, this looks good

2020-12-23 16:51 UTC, merged

2020-12-23 17:09 UTC, n0madic commented
[i meant it](https://github.com/n0madic/twitter-scraper/commit/922ccc5a874216834331ef8d5bf3c627225c1081)

2020-12-23 17:56 UTC, n0madic commented
[Changed mode selection to enum](https://github.com/n0madic/twitter-scraper/commit/1d3f84fc4ac93da53c7d0899bf7bef5b1d9c1712)